export const products=[
    {id:0,
        nombre_producto:"Fresas",
        cantidad_producto:234,
        fecha_vencimiento:"23-10-2024",
        imagen:"/products/jelena-mirkovic-llEyrvexG3I-unsplash.jpg",
        agotado:false,
        description:"som Fresas frescas recien cosechadas del tropico",
        centro:"Centro 1",
        precio:123,
        type:"Productora",     
    },
    {id:1,
        nombre_producto:"Hamburguesa",
        cantidad_producto:134,
        fecha_vencimiento:"27-10-2024",
        imagen:"/products/mae-mu-E1yr3ph1kSU-unsplash.jpg",
        agotado:false,
        description:"las delicias de nuestro negocio hare relumbrar su vista con la mejor oferta de hamburguesa",
        centro:"Centro 1",
        precio:345,
        type:"Productora",     
    },
    {id:2,
        nombre_producto:"Huevos ",
        cantidad_producto:134,
        fecha_vencimiento:"26-10-2024",
        imagen:"/products/mae-mu-en4qp-aK1h4-unsplash.jpg",
        agotado:false,
        description:"las delicias de nuestro negocio hare relumbrar su vista con la mejor oferta de huevos",
        centro:"Centro 1",
        precio:21,
        type:"Productora",     
    },
    {id:3,
        nombre_producto:"Naranjas",
        cantidad_producto:134,
        fecha_vencimiento:"26-10-2024",
        imagen:"/products/mae-mu-hkMGgTVBTSA-unsplash.jpg",
        agotado:false,
        description:"Naranjas recien cosechadas del tropico",
        centro:"Centro 1",
        precio:13,
        type:"Productora",     
    },
]